### ISSUE TITLE
Jsososo QQ音乐失效

### ISSUE THREAD

**Issue by Liqianyu** [zhengfan2014/xbmc-kodi-private-china-addons#37]
**描述错误**
网易云正常，QQ音乐无法获取排行、歌单、搜索、私享
QQ音乐 MV似乎正常、私享成功获取[该歌单](https://y.qq.com/n/ryqq/playlist/8131032480)，其他都无法获取。

**重现**
重现行为的步骤:
1. 去 'Jsososo插件'
2. 点击 '排行'
3. 划到 'QQ音乐任意排行榜'
4. 出错

**预期行为**
正常获取播放

**屏幕截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**设备信息**
 - 设备: 移动魔百盒
 - 系统: Android 4.4.2
 - Kodi 版本: Kodi 17.1(MyGica Fork) 

**其他**
应该和设备系统和Kodi版本无关。

报错日志
`15:05:20.293 T:2003763120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('data',)
                                            Traceback (most recent call last):
                                              File "/mnt/sdcard/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.jsososo/addon.py", line 1527, in <module>
                                                plugin.run()
                                              File "/mnt/sdcard/Android/data/mygica.media.center/files/.mygica/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "/mnt/sdcard/Android/data/mygica.media.center/files/.mygica/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 316, in _dispatch
                                                listitems = view_func(**items)
                                              File "/mnt/sdcard/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.jsososo/addon.py", line 1150, in playlist
                                                gdlist = qqplaylist(pid)
                                              File "/mnt/sdcard/Android/data/mygica.media.center/files/.mygica/addons/plugin.audio.jsososo/addon.py", line 331, in qqplaylist
                                                mp3urls = j1['data']
                                            KeyError: ('data',)
                                            -->End of Python script error report<--`

**Comment by ArchieMeng** [comment]
能拿到Log吗？

**Comment by Liqianyu** [comment]
@ArchieMeng 
可以，已经贴上了日志。成功获取的歌单也贴上了。
没明白这个歌单有何特殊。新建了空白的歌单测试也会报错。
